### PR TITLE
add the getMorphClass() function

### PR DESCRIPTION
**Pull request by phpcxy**
Thank you for helping to make this package better!

Please make sure you've read [CONTRIBUTING.md](https://github.com/cviebrock/eloquent-sluggable/blob/master/CONTRIBUTING.md) 
before submitting your pull request, and that you have:

- [x] provided a rationale for your change (I try not to add features that are going to have a limited user-base)
- [x] used the [PSR-2 Coding Standard](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md)
- [x] added tests
- [x] documented any change in behaviour (e.g. updated the `README.md`, etc.)
- [x] only submitted one pull request per feature

**Thank you!**

### CODE REVIEW

**Comment by cviebrock** [comment]
Can you explain what this change does, rather than using `static::class`?

**Comment by phpcxy** [comment]
@cviebrock

**Comment by phpcxy** [comment]
@cviebrock 
https://laravel.com/docs/5.5/eloquent-relationships#polymorphic-relations
If i define the `Custom Polymorphic Types`, this function can get the custom name instead of the class name.

**Comment by cviebrock** [comment]
Thanks!

**Pull request merged**
