### PR TITLE
Events when a model is Tagged or Untagged.

### PR DESCRIPTION
**Pull request by devguar**
Events when a model is Tagged or Untagged.

This way we can trigger an event based on 'when' and 'where' a model is tagged or untagged.

-----

Thank you for helping to make this package better!

Please make sure you've read [CONTRIBUTING.md](https://github.com/cviebrock/eloquent-sluggable/blob/master/CONTRIBUTING.md) 
before submitting your pull request, and that you have:

- [x] provided a rationale for your change (I try not to add features that are going to have a limited user-base)
- [x] used the [PSR-2 Coding Standard](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md)
- [x] added tests **the same tests can be used normally**
- [x] documented any change in behaviour (e.g. updated the `README.md`, etc.)
- [x] only submitted one pull request per feature

**Thank you!**

### CODE REVIEW

**Comment by cviebrock** [comment]
Two questions:

1. Do the events need setters for the model and tags? Seems like these should be set in the constructor and nowhere else. 

2. Tests?

Otherwise, this is a great addition!

**Comment by devguar** [comment]
> Two questions:
> 
> 1. Do the events need setters for the model and tags? Seems like these should be set in the constructor and nowhere else.
> 2. Tests?
> 
> Otherwise, this is a great addition!

Yes you are right, we dont need that methods on events. So I removed.
About the tests, I ran the same test we already have in the repository, you think we should have new tests for this?

**Comment by devguar** [comment]
Hey guys, this will be merged into master?

**Comment by cviebrock** [comment]
Slipped my mind ... merged now. Will tidy things up a bit and push a release shortly.  Thanks!

**Comment by cviebrock** [comment]
Version 3.6.0 includes the events now.  Thanks again!

**Comment by devguar** [comment]
Great! thank you @cviebrock

**Comment by devguar** [comment]
Hi @cviebrock , Im using laravel 5.7, can I merge this changes (this PL and https://github.com/cviebrock/eloquent-taggable/pull/90) into version 3.4.*?

**Comment by cviebrock** [comment]
Yes, just make another PR for that please, against the (new) `3.4` branch.

**Pull request merged**
